# Compiler
CC := clang

# Directories
SRC_DIR   := ./src
BUILD_DIR := ./build

# Settings
TARGET := cxx
CFLAGS := -Wall -Wextra -Werror -std=c23 -fno-common
CFLAGS += -D_GNU_SOURCE
CFLAGS += -I$(SRC_DIR)
LDFLAGS :=

# Debug flags
DEBUG ?= 1
ifeq ($(DEBUG), 0)
CFLAGS += -O2 -DNDEBUG
else
CFLAGS += -g -O0
endif

# Source files
SRCS := $(shell find $(SRC_DIR) -name '*.c')
OBJS := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRCS))
OBJS_DIRS := $(sort $(dir $(OBJS)))

# Generated headers (from tools scripts or the host machine)
GENERATED_HDRS := src/width_property.h src/xid_property.h src/pow_table.h src/config.h

# All headers (existing + generated)
HDRS := $(wildcard $(SRC_DIR)/*.h)

TEST_SRCS := $(filter-out test/rv32_common.c test/rv32_tf3.c,$(wildcard test/*.c))
TESTS := $(TEST_SRCS:.c=.out)

ALL_SRCS := $(SRCS) $(HDRS)

DEPS := $(OBJS:.o=.d)
CPPFLAGS := -MMD -MP

# Main target
$(TARGET): $(OBJS)
	$(CC) $^ $(LDFLAGS) -o $@

$(BUILD_DIR)/lexer.o: | src/pow_table.h
$(BUILD_DIR)/unicode.o: | src/width_property.h src/xid_property.h
$(BUILD_DIR)/main.o: | src/config.h

# C source compilation
define c_recipe
	mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@
endef

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c ; $(c_recipe)

# Rules to generate headers from scripts
src/width_property.h: tools/extract_width.py
	python3 $< > $@

src/xid_property.h: tools/extract_xid.py
	python3 $< > $@

src/pow_table.h: tools/gen_pow_table.py
	python3 $< > $@

# config.h is generated from the host machine's triple so a native
# build works on any architecture. When the host cannot be detected,
# the build stops and asks for a manual src/config.h instead.
.PHONY: FORCE
FORCE:

src/config.h: FORCE
	@host=$$($(CC) -dumpmachine 2>/dev/null || true); \
	 def=; \
	 case "$$host" in \
	   x86_64*)  def=T_amd64 ;; \
	   aarch64*) def=T_arm64 ;; \
	   riscv64*) def=T_rv64 ;; \
	   riscv32*) def=T_rv32 ;; \
	 esac; \
	 if [ -n "$$def" ]; then \
	   { echo "// Generated by make from the host triple ('$$host')."; \
	     echo "// If host detection fails, create this file manually, e.g.:"; \
	     echo "//   #define Deftgt T_amd64"; \
	     echo "#define Deftgt $$def"; } > $@.tmp; \
	   if ! cmp -s $@.tmp $@ 2>/dev/null; then mv $@.tmp $@; else rm -f $@.tmp; fi; \
	 elif [ ! -f $@ ]; then \
	   echo "error: cannot detect the host architecture ('$(CC) -dumpmachine' failed)" >&2; \
	   echo "create src/config.h manually, e.g.:" >&2; \
	   echo "  #define Deftgt T_amd64" >&2; \
	   exit 1; \
	 fi

.PHONY: test test-amd64 test-arm64 test-rv64 test-rv32 test-all clean linecnt fmt

test/%.out: $(TARGET) test/%.c
	./$(TARGET) -Itest -c -o test/$*.o test/$*.c
	$(CC) -o $@ test/$*.o -xc test/common

test: $(TARGET) $(TESTS)
	@for i in $(TESTS); do echo "Running $$i"; $$i || exit 1; echo; done
	@bash test/driver.sh ./cxx

# Cross-architecture suites. amd64/arm64/rv64 run under qemu user-mode
# (test/run_cross.sh); rv32 uses the bare-metal harness (test/run_rv32.sh).
# Each suite SKIPs itself on a host of the same architecture (native
# coverage is `make test`).
test-amd64: $(TARGET)
	@bash test/run_cross.sh amd64

test-arm64: $(TARGET)
	@bash test/run_cross.sh arm64

test-rv64: $(TARGET)
	@bash test/run_cross.sh rv64

test-rv32: $(TARGET)
	@bash test/run_rv32.sh

test-all: test test-amd64 test-arm64 test-rv64 test-rv32

clean:
	-rm -rf $(TARGET) $(BUILD_DIR) test/*.out test/*.ll test/*.o $(GENERATED_HDRS)

linecnt:
	@echo "Total lines of code (excluding blank lines and // comments):"
	@cat $(ALL_SRCS) | sed 's|//.*$$||' | grep -v '^[[:space:]]*$$' | wc -l

fmt:
	@which clang-format-21 > /dev/null || { echo "clang-format not found"; exit 1; }
	clang-format-21 -i $(ALL_SRCS) $(TEST_SRCS)
	@echo "Formatted $(words $(ALL_SRCS)) files."

-include $(DEPS)
