#include "cxx.h"

#define TYPE(a, b, c, d)  \
    {                     \
        .kind = a,        \
        .size = b,        \
        .align = c,       \
        .is_unsigned = d, \
    }

static Type ty_none_ = TYPE(TY_NONE, -1, 1, false);
static Type ty_void_ = TYPE(TY_VOID, 1, 1, false);
static Type ty_nullptr_ = TYPE(TY_NULLPTR, 4, 4, true);
static Type ty_bool_ = TYPE(TY_BOOL, 1, 1, true);
static Type ty_char_ = TYPE(TY_CHAR, 1, 1, true);
static Type ty_schar_ = TYPE(TY_SCHAR, 1, 1, false);
static Type ty_uchar_ = TYPE(TY_UCHAR, 1, 1, true);
static Type ty_short_ = TYPE(TY_SHORT, 2, 2, false);
static Type ty_ushort_ = TYPE(TY_SHORT, 2, 2, true);
static Type ty_int_ = TYPE(TY_INT, 4, 4, false);
static Type ty_uint_ = TYPE(TY_INT, 4, 4, true);
static Type ty_long_ = TYPE(TY_LONG, 4, 4, false);
static Type ty_ulong_ = TYPE(TY_LONG, 4, 4, true);
static Type ty_llong_ = TYPE(TY_LLONG, 8, 8, false);
static Type ty_ullong_ = TYPE(TY_LLONG, 8, 8, true);
static Type ty_float_ = TYPE(TY_FLOAT, 4, 4, false);
static Type ty_double_ = TYPE(TY_DOUBLE, 8, 8, false);
static Type ty_ldouble_ = TYPE(TY_LDOUBLE, 16, 16, false);

#undef TYPE

Target T_rv32 = {
    .llvm_features = "\"+m,+a,+f,+d,+c\"",
    .llvm_abi = "\"ilp32d\"",
    .clang_mabi = "ilp32d",
    .clang_march = "rv32imafdc",
    .ldouble_is_fp80 = false,
    .name = "rv32",
    .triple = "riscv32-linux-gnu",
    .datalayout = "e-m:e-p:32:32-i64:64-n32-S128",
    .sysroot = NULL,
    .ty_none = &ty_none_,
    .ty_void = &ty_void_,
    .ty_nullptr = &ty_nullptr_,
    .ty_bool = &ty_bool_,
    .ty_char = &ty_char_,
    .ty_schar = &ty_schar_,
    .ty_uchar = &ty_uchar_,
    .ty_short = &ty_short_,
    .ty_ushort = &ty_ushort_,
    .ty_int = &ty_int_,
    .ty_uint = &ty_uint_,
    .ty_long = &ty_long_,
    .ty_ulong = &ty_ulong_,
    .ty_llong = &ty_llong_,
    .ty_ullong = &ty_ullong_,
    .ty_float = &ty_float_,
    .ty_double = &ty_double_,
    .ty_ldouble = &ty_ldouble_,
    .ty_wchar = &ty_int_,
    .int_max = 2147483647,
    .uint_max = 4294967295U,
    .long_max = 2147483647L,
    .ulong_max = 4294967295UL,
    .llong_max = 9223372036854775807LL,
    .predef =
        "#define _ILP32 1\n"
        "#define __ATOMIC_ACQUIRE 2\n"
        "#define __ATOMIC_ACQ_REL 4\n"
        "#define __ATOMIC_CONSUME 1\n"
        "#define __ATOMIC_RELAXED 0\n"
        "#define __ATOMIC_RELEASE 3\n"
        "#define __ATOMIC_SEQ_CST 5\n"
        "#define __BIGGEST_ALIGNMENT__ 16\n"
        "#define __BITINT_MAXWIDTH__ 128\n"
        "#define __BOOL_WIDTH__ 1\n"
        "#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__\n"
        "#define __CHAR16_TYPE__ unsigned short\n"
        "#define __CHAR32_TYPE__ unsigned int\n"
        "#define __CHAR_BIT__ 8\n"
        "#define __CHAR_UNSIGNED__ 1\n"
        "#define __DBL_DECIMAL_DIG__ 17\n"
        "#define __DBL_DENORM_MIN__ 4.9406564584124654e-324\n"
        "#define __DBL_DIG__ 15\n"
        "#define __DBL_EPSILON__ 2.2204460492503131e-16\n"
        "#define __DBL_HAS_DENORM__ 1\n"
        "#define __DBL_HAS_INFINITY__ 1\n"
        "#define __DBL_HAS_QUIET_NAN__ 1\n"
        "#define __DBL_MANT_DIG__ 53\n"
        "#define __DBL_MAX_10_EXP__ 308\n"
        "#define __DBL_MAX_EXP__ 1024\n"
        "#define __DBL_MAX__ 1.7976931348623157e+308\n"
        "#define __DBL_MIN_10_EXP__ (-307)\n"
        "#define __DBL_MIN_EXP__ (-1021)\n"
        "#define __DBL_MIN__ 2.2250738585072014e-308\n"
        "#define __DBL_NORM_MAX__ 1.7976931348623157e+308\n"
        "#define __DECIMAL_DIG__ __LDBL_DECIMAL_DIG__\n"
        "#define __ELF__ 1\n"
        "#define __FINITE_MATH_ONLY__ 0\n"
        "#define __FLT16_DECIMAL_DIG__ 5\n"
        "#define __FLT16_DENORM_MIN__ 5.9604644775390625e-8F16\n"
        "#define __FLT16_DIG__ 3\n"
        "#define __FLT16_EPSILON__ 9.765625e-4F16\n"
        "#define __FLT16_HAS_DENORM__ 1\n"
        "#define __FLT16_HAS_INFINITY__ 1\n"
        "#define __FLT16_HAS_QUIET_NAN__ 1\n"
        "#define __FLT16_MANT_DIG__ 11\n"
        "#define __FLT16_MAX_10_EXP__ 4\n"
        "#define __FLT16_MAX_EXP__ 16\n"
        "#define __FLT16_MAX__ 6.5504e+4F16\n"
        "#define __FLT16_MIN_10_EXP__ (-4)\n"
        "#define __FLT16_MIN_EXP__ (-13)\n"
        "#define __FLT16_MIN__ 6.103515625e-5F16\n"
        "#define __FLT16_NORM_MAX__ 6.5504e+4F16\n"
        "#define __FLT_DECIMAL_DIG__ 9\n"
        "#define __FLT_DENORM_MIN__ 1.40129846e-45F\n"
        "#define __FLT_DIG__ 6\n"
        "#define __FLT_EPSILON__ 1.19209290e-7F\n"
        "#define __FLT_HAS_DENORM__ 1\n"
        "#define __FLT_HAS_INFINITY__ 1\n"
        "#define __FLT_HAS_QUIET_NAN__ 1\n"
        "#define __FLT_MANT_DIG__ 24\n"
        "#define __FLT_MAX_10_EXP__ 38\n"
        "#define __FLT_MAX_EXP__ 128\n"
        "#define __FLT_MAX__ 3.40282347e+38F\n"
        "#define __FLT_MIN_10_EXP__ (-37)\n"
        "#define __FLT_MIN_EXP__ (-125)\n"
        "#define __FLT_MIN__ 1.17549435e-38F\n"
        "#define __FLT_NORM_MAX__ 3.40282347e+38F\n"
        "#define __FLT_RADIX__ 2\n"
        "#define __FPCLASS_NEGINF 0x0004\n"
        "#define __FPCLASS_NEGNORMAL 0x0008\n"
        "#define __FPCLASS_NEGSUBNORMAL 0x0010\n"
        "#define __FPCLASS_NEGZERO 0x0020\n"
        "#define __FPCLASS_POSINF 0x0200\n"
        "#define __FPCLASS_POSNORMAL 0x0100\n"
        "#define __FPCLASS_POSSUBNORMAL 0x0080\n"
        "#define __FPCLASS_POSZERO 0x0040\n"
        "#define __FPCLASS_QNAN 0x0002\n"
        "#define __FPCLASS_SNAN 0x0001\n"

        "#define __ILP32__ 1\n"
        "#define __INT16_C(c) c\n"
        "#define __INT16_C_SUFFIX__ \n"
        "#define __INT16_FMTd__ \"hd\"\n"
        "#define __INT16_FMTi__ \"hi\"\n"
        "#define __INT16_MAX__ 32767\n"
        "#define __INT16_TYPE__ short\n"
        "#define __INT32_C(c) c\n"
        "#define __INT32_C_SUFFIX__ \n"
        "#define __INT32_FMTd__ \"d\"\n"
        "#define __INT32_FMTi__ \"i\"\n"
        "#define __INT32_MAX__ 2147483647\n"
        "#define __INT32_TYPE__ int\n"
        "#define __INT64_C(c) c##LL\n"
        "#define __INT64_C_SUFFIX__ LL\n"
        "#define __INT64_FMTd__ \"lld\"\n"
        "#define __INT64_FMTi__ \"lli\"\n"
        "#define __INT64_MAX__ 9223372036854775807LL\n"
        "#define __INT64_TYPE__ long long int\n"
        "#define __INT8_C(c) c\n"
        "#define __INT8_C_SUFFIX__ \n"
        "#define __INT8_FMTd__ \"hhd\"\n"
        "#define __INT8_FMTi__ \"hhi\"\n"
        "#define __INT8_MAX__ 127\n"
        "#define __INT8_TYPE__ signed char\n"
        "#define __INTMAX_C(c) c##LL\n"
        "#define __INTMAX_C_SUFFIX__ LL\n"
        "#define __INTMAX_FMTd__ \"lld\"\n"
        "#define __INTMAX_FMTi__ \"lli\"\n"
        "#define __INTMAX_MAX__ 9223372036854775807LL\n"
        "#define __INTMAX_TYPE__ long long int\n"
        "#define __INTMAX_WIDTH__ 64\n"
        "#define __INTPTR_FMTd__ \"d\"\n"
        "#define __INTPTR_FMTi__ \"i\"\n"
        "#define __INTPTR_MAX__ 2147483647\n"
        "#define __INTPTR_TYPE__ int\n"
        "#define __INTPTR_WIDTH__ 32\n"
        "#define __INT_FAST16_FMTd__ \"hd\"\n"
        "#define __INT_FAST16_FMTi__ \"hi\"\n"
        "#define __INT_FAST16_MAX__ 32767\n"
        "#define __INT_FAST16_TYPE__ short\n"
        "#define __INT_FAST16_WIDTH__ 16\n"
        "#define __INT_FAST32_FMTd__ \"d\"\n"
        "#define __INT_FAST32_FMTi__ \"i\"\n"
        "#define __INT_FAST32_MAX__ 2147483647\n"
        "#define __INT_FAST32_TYPE__ int\n"
        "#define __INT_FAST32_WIDTH__ 32\n"
        "#define __INT_FAST64_FMTd__ \"lld\"\n"
        "#define __INT_FAST64_FMTi__ \"lli\"\n"
        "#define __INT_FAST64_MAX__ 9223372036854775807LL\n"
        "#define __INT_FAST64_TYPE__ long long int\n"
        "#define __INT_FAST64_WIDTH__ 64\n"
        "#define __INT_FAST8_FMTd__ \"hhd\"\n"
        "#define __INT_FAST8_FMTi__ \"hhi\"\n"
        "#define __INT_FAST8_MAX__ 127\n"
        "#define __INT_FAST8_TYPE__ signed char\n"
        "#define __INT_FAST8_WIDTH__ 8\n"
        "#define __INT_LEAST16_FMTd__ \"hd\"\n"
        "#define __INT_LEAST16_FMTi__ \"hi\"\n"
        "#define __INT_LEAST16_MAX__ 32767\n"
        "#define __INT_LEAST16_TYPE__ short\n"
        "#define __INT_LEAST16_WIDTH__ 16\n"
        "#define __INT_LEAST32_FMTd__ \"d\"\n"
        "#define __INT_LEAST32_FMTi__ \"i\"\n"
        "#define __INT_LEAST32_MAX__ 2147483647\n"
        "#define __INT_LEAST32_TYPE__ int\n"
        "#define __INT_LEAST32_WIDTH__ 32\n"
        "#define __INT_LEAST64_FMTd__ \"lld\"\n"
        "#define __INT_LEAST64_FMTi__ \"lli\"\n"
        "#define __INT_LEAST64_MAX__ 9223372036854775807LL\n"
        "#define __INT_LEAST64_TYPE__ long long int\n"
        "#define __INT_LEAST64_WIDTH__ 64\n"
        "#define __INT_LEAST8_FMTd__ \"hhd\"\n"
        "#define __INT_LEAST8_FMTi__ \"hhi\"\n"
        "#define __INT_LEAST8_MAX__ 127\n"
        "#define __INT_LEAST8_TYPE__ signed char\n"
        "#define __INT_LEAST8_WIDTH__ 8\n"
        "#define __INT_MAX__ 2147483647\n"
        "#define __INT_WIDTH__ 32\n"
        "#define __LDBL_DECIMAL_DIG__ 36\n"
        "#define __LDBL_DENORM_MIN__ 6.47517511943802511092443895822764655e-4966L\n"
        "#define __LDBL_DIG__ 33\n"
        "#define __LDBL_EPSILON__ 1.92592994438723585305597794258492732e-34L\n"
        "#define __LDBL_HAS_DENORM__ 1\n"
        "#define __LDBL_HAS_INFINITY__ 1\n"
        "#define __LDBL_HAS_QUIET_NAN__ 1\n"
        "#define __LDBL_MANT_DIG__ 113\n"
        "#define __LDBL_MAX_10_EXP__ 4932\n"
        "#define __LDBL_MAX_EXP__ 16384\n"
        "#define __LDBL_MAX__ 1.18973149535723176508575932662800702e+4932L\n"
        "#define __LDBL_MIN_10_EXP__ (-4931)\n"
        "#define __LDBL_MIN_EXP__ (-16381)\n"
        "#define __LDBL_MIN__ 3.36210314311209350626267781732175260e-4932L\n"
        "#define __LDBL_NORM_MAX__ 1.18973149535723176508575932662800702e+4932L\n"
        "#define __LITTLE_ENDIAN__ 1\n"
        "#define __LLONG_WIDTH__ 64\n"
        "#define __LONG_LONG_MAX__ 9223372036854775807LL\n"
        "#define __LONG_MAX__ 2147483647L\n"
        "#define __LONG_WIDTH__ 32\n"

        "#define __ORDER_BIG_ENDIAN__ 4321\n"
        "#define __ORDER_LITTLE_ENDIAN__ 1234\n"
        "#define __ORDER_PDP_ENDIAN__ 3412\n"
        "#define __FLT32_DECIMAL_DIG__ 9\n"
        "#define __FLT32_DENORM_MIN__ 0x1p-149f32\n"
        "#define __FLT32_DIG__ 6\n"
        "#define __FLT32_EPSILON__ 0x1p-23f32\n"
        "#define __FLT32_HAS_DENORM__ 1\n"
        "#define __FLT32_HAS_INFINITY__ 1\n"
        "#define __FLT32_HAS_QUIET_NAN__ 1\n"
        "#define __FLT32_MANT_DIG__ 24\n"
        "#define __FLT32_MAX_10_EXP__ 38\n"
        "#define __FLT32_MAX_EXP__ 128\n"
        "#define __FLT32_MAX__ 0x1.fffffep+127f32\n"
        "#define __FLT32_MIN_10_EXP__ (-37)\n"
        "#define __FLT32_MIN_EXP__ (-125)\n"
        "#define __FLT32_MIN__ 0x1p-126f32\n"
        "#define __FLT32_NORM_MAX__ 0x1.fffffep+127f32\n"
        "#define __FLT64_DECIMAL_DIG__ 17\n"
        "#define __FLT64_DENORM_MIN__ 0x0.0000000000001p-1022f64\n"
        "#define __FLT64_DIG__ 15\n"
        "#define __FLT64_EPSILON__ 0x1p-52f64\n"
        "#define __FLT64_HAS_DENORM__ 1\n"
        "#define __FLT64_HAS_INFINITY__ 1\n"
        "#define __FLT64_HAS_QUIET_NAN__ 1\n"
        "#define __FLT64_MANT_DIG__ 53\n"
        "#define __FLT64_MAX_10_EXP__ 308\n"
        "#define __FLT64_MAX_EXP__ 1024\n"
        "#define __FLT64_MAX__ 0x1.fffffffffffffp+1023f64\n"
        "#define __FLT64_MIN_10_EXP__ (-307)\n"
        "#define __FLT64_MIN_EXP__ (-1021)\n"
        "#define __FLT64_MIN__ 0x1p-1022f64\n"
        "#define __FLT64_NORM_MAX__ 0x1.fffffffffffffp+1023f64\n"
        "#define __FLT128_DECIMAL_DIG__ 36\n"
        "#define __FLT128_DENORM_MIN__ 0x1p-16494f128\n"
        "#define __FLT128_DIG__ 33\n"
        "#define __FLT128_EPSILON__ 0x1p-112f128\n"
        "#define __FLT128_HAS_DENORM__ 1\n"
        "#define __FLT128_HAS_INFINITY__ 1\n"
        "#define __FLT128_HAS_QUIET_NAN__ 1\n"
        "#define __FLT128_MANT_DIG__ 113\n"
        "#define __FLT128_MAX_10_EXP__ 4932\n"
        "#define __FLT128_MAX_EXP__ 16384\n"
        "#define __FLT128_MAX__ 0x1.ffffffffffffffffffffffffffffp+16383f128\n"
        "#define __FLT128_MIN_10_EXP__ (-4931)\n"
        "#define __FLT128_MIN_EXP__ (-16381)\n"
        "#define __FLT128_MIN__ 0x1p-16382f128\n"
        "#define __FLT128_NORM_MAX__ 0x1.ffffffffffffffffffffffffffffp+16383f128\n"
        "#define __PIC__ 2\n"
        "#define __PIE__ 2\n"
        "#define __POINTER_WIDTH__ 32\n"

        "#define __PTRDIFF_FMTd__ \"d\"\n"
        "#define __PTRDIFF_FMTi__ \"i\"\n"
        "#define __PTRDIFF_MAX__ 2147483647\n"
        "#define __PTRDIFF_TYPE__ int\n"
        "#define __PTRDIFF_WIDTH__ 32\n"
        "#define __SCHAR_MAX__ 127\n"
        "#define __SHRT_MAX__ 32767\n"
        "#define __SHRT_WIDTH__ 16\n"
        "#define __SIG_ATOMIC_MAX__ 2147483647\n"
        "#define __SIG_ATOMIC_WIDTH__ 32\n"
        "#define __SIZEOF_DOUBLE__ 8\n"
        "#define __SIZEOF_FLOAT__ 4\n"
        "#define __SIZEOF_INT__ 4\n"
        "#define __SIZEOF_LONG_DOUBLE__ 16\n"
        "#define __SIZEOF_LONG_LONG__ 8\n"
        "#define __SIZEOF_LONG__ 4\n"
        "#define __SIZEOF_POINTER__ 4\n"
        "#define __SIZEOF_PTRDIFF_T__ 4\n"
        "#define __SIZEOF_SHORT__ 2\n"
        "#define __SIZEOF_SIZE_T__ 4\n"
        "#define __SIZEOF_WCHAR_T__ 4\n"
        "#define __SIZEOF_WINT_T__ 4\n"
        "#define __SIZE_FMTX__ \"X\"\n"
        "#define __SIZE_FMTo__ \"o\"\n"
        "#define __SIZE_FMTu__ \"u\"\n"
        "#define __SIZE_FMTx__ \"x\"\n"
        "#define __SIZE_MAX__ 4294967295U\n"
        "#define __SIZE_TYPE__ unsigned int\n"
        "#define __SIZE_WIDTH__ 32\n"
        "#define __STDC_EMBED_EMPTY__ 2\n"
        "#define __STDC_EMBED_FOUND__ 1\n"
        "#define __STDC_EMBED_NOT_FOUND__ 0\n"
        "#define __STDC_HOSTED__ 1\n"
        "#define __STDC_UTF_16__ 1\n"
        "#define __STDC_UTF_32__ 1\n"
        "#define __STDC_VERSION__ 201710L\n"
        "#define __STDC__ 1\n"
        "#define __UINT16_C(c) c\n"
        "#define __UINT16_C_SUFFIX__ \n"
        "#define __UINT16_FMTX__ \"hX\"\n"
        "#define __UINT16_FMTo__ \"ho\"\n"
        "#define __UINT16_FMTu__ \"hu\"\n"
        "#define __UINT16_FMTx__ \"hx\"\n"
        "#define __UINT16_MAX__ 65535\n"
        "#define __UINT16_TYPE__ unsigned short\n"
        "#define __UINT32_C(c) c##U\n"
        "#define __UINT32_C_SUFFIX__ U\n"
        "#define __UINT32_FMTX__ \"X\"\n"
        "#define __UINT32_FMTo__ \"o\"\n"
        "#define __UINT32_FMTu__ \"u\"\n"
        "#define __UINT32_FMTx__ \"x\"\n"
        "#define __UINT32_MAX__ 4294967295U\n"
        "#define __UINT32_TYPE__ unsigned int\n"
        "#define __UINT64_C(c) c##ULL\n"
        "#define __UINT64_C_SUFFIX__ ULL\n"
        "#define __UINT64_FMTX__ \"llX\"\n"
        "#define __UINT64_FMTo__ \"llo\"\n"
        "#define __UINT64_FMTu__ \"llu\"\n"
        "#define __UINT64_FMTx__ \"llx\"\n"
        "#define __UINT64_MAX__ 18446744073709551615ULL\n"
        "#define __UINT64_TYPE__ long long unsigned int\n"
        "#define __UINT8_C(c) c\n"
        "#define __UINT8_C_SUFFIX__ \n"
        "#define __UINT8_FMTX__ \"hhX\"\n"
        "#define __UINT8_FMTo__ \"hho\"\n"
        "#define __UINT8_FMTu__ \"hhu\"\n"
        "#define __UINT8_FMTx__ \"hhx\"\n"
        "#define __UINT8_MAX__ 255\n"
        "#define __UINT8_TYPE__ unsigned char\n"
        "#define __UINTMAX_C(c) c##ULL\n"
        "#define __UINTMAX_C_SUFFIX__ ULL\n"
        "#define __UINTMAX_FMTX__ \"llX\"\n"
        "#define __UINTMAX_FMTo__ \"llo\"\n"
        "#define __UINTMAX_FMTu__ \"llu\"\n"
        "#define __UINTMAX_FMTx__ \"llx\"\n"
        "#define __UINTMAX_MAX__ 18446744073709551615ULL\n"
        "#define __UINTMAX_TYPE__ long long unsigned int\n"
        "#define __UINTMAX_WIDTH__ 64\n"
        "#define __UINTPTR_FMTX__ \"X\"\n"
        "#define __UINTPTR_FMTo__ \"o\"\n"
        "#define __UINTPTR_FMTu__ \"u\"\n"
        "#define __UINTPTR_FMTx__ \"x\"\n"
        "#define __UINTPTR_MAX__ 4294967295U\n"
        "#define __UINTPTR_TYPE__ unsigned int\n"
        "#define __UINTPTR_WIDTH__ 32\n"
        "#define __UINT_FAST16_FMTX__ \"hX\"\n"
        "#define __UINT_FAST16_FMTo__ \"ho\"\n"
        "#define __UINT_FAST16_FMTu__ \"hu\"\n"
        "#define __UINT_FAST16_FMTx__ \"hx\"\n"
        "#define __UINT_FAST16_MAX__ 65535\n"
        "#define __UINT_FAST16_TYPE__ unsigned short\n"
        "#define __UINT_FAST32_FMTX__ \"X\"\n"
        "#define __UINT_FAST32_FMTo__ \"o\"\n"
        "#define __UINT_FAST32_FMTu__ \"u\"\n"
        "#define __UINT_FAST32_FMTx__ \"x\"\n"
        "#define __UINT_FAST32_MAX__ 4294967295U\n"
        "#define __UINT_FAST32_TYPE__ unsigned int\n"
        "#define __UINT_FAST64_FMTX__ \"llX\"\n"
        "#define __UINT_FAST64_FMTo__ \"llo\"\n"
        "#define __UINT_FAST64_FMTu__ \"llu\"\n"
        "#define __UINT_FAST64_FMTx__ \"llx\"\n"
        "#define __UINT_FAST64_MAX__ 18446744073709551615ULL\n"
        "#define __UINT_FAST64_TYPE__ long long unsigned int\n"
        "#define __UINT_FAST8_FMTX__ \"hhX\"\n"
        "#define __UINT_FAST8_FMTo__ \"hho\"\n"
        "#define __UINT_FAST8_FMTu__ \"hhu\"\n"
        "#define __UINT_FAST8_FMTx__ \"hhx\"\n"
        "#define __UINT_FAST8_MAX__ 255\n"
        "#define __UINT_FAST8_TYPE__ unsigned char\n"
        "#define __UINT_LEAST16_FMTX__ \"hX\"\n"
        "#define __UINT_LEAST16_FMTo__ \"ho\"\n"
        "#define __UINT_LEAST16_FMTu__ \"hu\"\n"
        "#define __UINT_LEAST16_FMTx__ \"hx\"\n"
        "#define __UINT_LEAST16_MAX__ 65535\n"
        "#define __UINT_LEAST16_TYPE__ unsigned short\n"
        "#define __UINT_LEAST32_FMTX__ \"X\"\n"
        "#define __UINT_LEAST32_FMTo__ \"o\"\n"
        "#define __UINT_LEAST32_FMTu__ \"u\"\n"
        "#define __UINT_LEAST32_FMTx__ \"x\"\n"
        "#define __UINT_LEAST32_MAX__ 4294967295U\n"
        "#define __UINT_LEAST32_TYPE__ unsigned int\n"
        "#define __UINT_LEAST64_FMTX__ \"llX\"\n"
        "#define __UINT_LEAST64_FMTo__ \"llo\"\n"
        "#define __UINT_LEAST64_FMTu__ \"llu\"\n"
        "#define __UINT_LEAST64_FMTx__ \"llx\"\n"
        "#define __UINT_LEAST64_MAX__ 18446744073709551615ULL\n"
        "#define __UINT_LEAST64_TYPE__ long long unsigned int\n"
        "#define __UINT_LEAST8_FMTX__ \"hhX\"\n"
        "#define __UINT_LEAST8_FMTo__ \"hho\"\n"
        "#define __UINT_LEAST8_FMTu__ \"hhu\"\n"
        "#define __UINT_LEAST8_FMTx__ \"hhx\"\n"
        "#define __UINT_LEAST8_MAX__ 255\n"
        "#define __UINT_LEAST8_TYPE__ unsigned char\n"
        "#define __USER_LABEL_PREFIX__ \n"
        "#define __WCHAR_MAX__ 2147483647\n"
        "#define __WCHAR_TYPE__ int\n"
        "#define __WCHAR_WIDTH__ 32\n"
        "#define __WINT_MAX__ 4294967295U\n"
        "#define __WINT_TYPE__ unsigned int\n"
        "#define __WINT_UNSIGNED__ 1\n"
        "#define __WINT_WIDTH__ 32\n"
        "#define __gnu_linux__ 1\n"
        "#define __linux 1\n"
        "#define __linux__ 1\n"
        "#define __pic__ 2\n"
        "#define __pie__ 2\n"
        "#define __riscv 1\n"
        "#define __riscv_a 2001000\n"
        "#define __riscv_arch_test 1\n"
        "#define __riscv_atomic 1\n"
        "#define __riscv_c 2000000\n"
        "#define __riscv_cmodel_medlow 1\n"
        "#define __riscv_compressed 1\n"
        "#define __riscv_d 2002000\n"
        "#define __riscv_div 1\n"
        "#define __riscv_f 2002000\n"
        "#define __riscv_fdiv 1\n"
        "#define __riscv_flen 64\n"
        "#define __riscv_float_abi_double 1\n"
        "#define __riscv_fsqrt 1\n"
        "#define __riscv_i 2001000\n"
        "#define __riscv_m 2000000\n"
        "#define __riscv_misaligned_avoid 1\n"
        "#define __riscv_mul 1\n"
        "#define __riscv_muldiv 1\n"
        "#define __riscv_v_intrinsic 1000000\n"
        "#define __riscv_xlen 32\n"
        "#define __riscv_zaamo 1000000\n"
        "#define __riscv_zalrsc 1000000\n"
        "#define __riscv_zca 1000000\n"
        "#define __riscv_zcd 1000000\n"
        "#define __riscv_zcf 1000000\n"
        "#define __riscv_zicsr 2000000\n"
        "#define __riscv_zmmul 1000000\n"
        "#define __unix 1\n"
        "#define __unix__ 1\n"
        "#define linux 1\n"
        "#define unix 1\n"
        "#define __cxx__ 1\n"
        "#define __STDC_NO_ATOMICS__ 1\n"
        "#define __STDC_NO_COMPLEX__ 1\n"
        "#define __alignof__ _Alignof\n"
        "#define __const__ const\n"
        "#define __has_include __has_include\n"
        "#define __inline__ inline\n"
        "#define __signed__ signed\n"
        "#define __typeof__ typeof\n"
        "#define __volatile__ volatile\n",
};

Target T_rv32b = {
    .llvm_features = "\"+m,+a,+f,+d,+c\"",
    .llvm_abi = "\"ilp32d\"",
    .clang_mabi = "ilp32d",
    .clang_march = "rv32imafdc",
    .ldouble_is_fp80 = false,
    .name = "rv32b",
    .triple = "riscv32-none-elf",
    .datalayout = "e-m:e-p:32:32-i64:64-n32-S128",
    .sysroot = NULL,
    .ty_none = &ty_none_,
    .ty_void = &ty_void_,
    .ty_nullptr = &ty_nullptr_,
    .ty_bool = &ty_bool_,
    .ty_char = &ty_char_,
    .ty_schar = &ty_schar_,
    .ty_uchar = &ty_uchar_,
    .ty_short = &ty_short_,
    .ty_ushort = &ty_ushort_,
    .ty_int = &ty_int_,
    .ty_uint = &ty_uint_,
    .ty_long = &ty_long_,
    .ty_ulong = &ty_ulong_,
    .ty_llong = &ty_llong_,
    .ty_ullong = &ty_ullong_,
    .ty_float = &ty_float_,
    .ty_double = &ty_double_,
    .ty_ldouble = &ty_ldouble_,
    .ty_wchar = &ty_int_,
    .int_max = 2147483647,
    .uint_max = 4294967295U,
    .long_max = 2147483647L,
    .ulong_max = 4294967295UL,
    .llong_max = 9223372036854775807LL,
    .predef =
        "#define _ILP32 1\n"
        "#define __ATOMIC_ACQUIRE 2\n"
        "#define __ATOMIC_ACQ_REL 4\n"
        "#define __ATOMIC_CONSUME 1\n"
        "#define __ATOMIC_RELAXED 0\n"
        "#define __ATOMIC_RELEASE 3\n"
        "#define __ATOMIC_SEQ_CST 5\n"
        "#define __BIGGEST_ALIGNMENT__ 16\n"
        "#define __BITINT_MAXWIDTH__ 128\n"
        "#define __BOOL_WIDTH__ 1\n"
        "#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__\n"
        "#define __CHAR16_TYPE__ unsigned short\n"
        "#define __CHAR32_TYPE__ unsigned int\n"
        "#define __CHAR_BIT__ 8\n"
        "#define __CHAR_UNSIGNED__ 1\n"

        "#define __DBL_DECIMAL_DIG__ 17\n"
        "#define __DBL_DENORM_MIN__ 4.9406564584124654e-324\n"
        "#define __DBL_DIG__ 15\n"
        "#define __DBL_EPSILON__ 2.2204460492503131e-16\n"
        "#define __DBL_HAS_DENORM__ 1\n"
        "#define __DBL_HAS_INFINITY__ 1\n"
        "#define __DBL_HAS_QUIET_NAN__ 1\n"
        "#define __DBL_MANT_DIG__ 53\n"
        "#define __DBL_MAX_10_EXP__ 308\n"
        "#define __DBL_MAX_EXP__ 1024\n"
        "#define __DBL_MAX__ 1.7976931348623157e+308\n"
        "#define __DBL_MIN_10_EXP__ (-307)\n"
        "#define __DBL_MIN_EXP__ (-1021)\n"
        "#define __DBL_MIN__ 2.2250738585072014e-308\n"
        "#define __DBL_NORM_MAX__ 1.7976931348623157e+308\n"
        "#define __DECIMAL_DIG__ __LDBL_DECIMAL_DIG__\n"
        "#define __ELF__ 1\n"
        "#define __FINITE_MATH_ONLY__ 0\n"
        "#define __FLT16_DECIMAL_DIG__ 5\n"
        "#define __FLT16_DENORM_MIN__ 5.9604644775390625e-8F16\n"
        "#define __FLT16_DIG__ 3\n"
        "#define __FLT16_EPSILON__ 9.765625e-4F16\n"
        "#define __FLT16_HAS_DENORM__ 1\n"
        "#define __FLT16_HAS_INFINITY__ 1\n"
        "#define __FLT16_HAS_QUIET_NAN__ 1\n"
        "#define __FLT16_MANT_DIG__ 11\n"
        "#define __FLT16_MAX_10_EXP__ 4\n"
        "#define __FLT16_MAX_EXP__ 16\n"
        "#define __FLT16_MAX__ 6.5504e+4F16\n"
        "#define __FLT16_MIN_10_EXP__ (-4)\n"
        "#define __FLT16_MIN_EXP__ (-13)\n"
        "#define __FLT16_MIN__ 6.103515625e-5F16\n"
        "#define __FLT16_NORM_MAX__ 6.5504e+4F16\n"
        "#define __FLT_DECIMAL_DIG__ 9\n"
        "#define __FLT_DENORM_MIN__ 1.40129846e-45F\n"
        "#define __FLT_DIG__ 6\n"
        "#define __FLT_EPSILON__ 1.19209290e-7F\n"
        "#define __FLT_HAS_DENORM__ 1\n"
        "#define __FLT_HAS_INFINITY__ 1\n"
        "#define __FLT_HAS_QUIET_NAN__ 1\n"
        "#define __FLT_MANT_DIG__ 24\n"
        "#define __FLT_MAX_10_EXP__ 38\n"
        "#define __FLT_MAX_EXP__ 128\n"
        "#define __FLT_MAX__ 3.40282347e+38F\n"
        "#define __FLT_MIN_10_EXP__ (-37)\n"
        "#define __FLT_MIN_EXP__ (-125)\n"
        "#define __FLT_MIN__ 1.17549435e-38F\n"
        "#define __FLT_NORM_MAX__ 3.40282347e+38F\n"
        "#define __FLT_RADIX__ 2\n"
        "#define __FPCLASS_NEGINF 0x0004\n"
        "#define __FPCLASS_NEGNORMAL 0x0008\n"
        "#define __FPCLASS_NEGSUBNORMAL 0x0010\n"
        "#define __FPCLASS_NEGZERO 0x0020\n"
        "#define __FPCLASS_POSINF 0x0200\n"
        "#define __FPCLASS_POSNORMAL 0x0100\n"
        "#define __FPCLASS_POSSUBNORMAL 0x0080\n"
        "#define __FPCLASS_POSZERO 0x0040\n"
        "#define __FPCLASS_QNAN 0x0002\n"
        "#define __FPCLASS_SNAN 0x0001\n"

        "#define __ILP32__ 1\n"
        "#define __INT16_C(c) c\n"
        "#define __INT16_C_SUFFIX__ \n"
        "#define __INT16_FMTd__ \"hd\"\n"
        "#define __INT16_FMTi__ \"hi\"\n"
        "#define __INT16_MAX__ 32767\n"
        "#define __INT16_TYPE__ short\n"
        "#define __INT32_C(c) c\n"
        "#define __INT32_C_SUFFIX__ \n"
        "#define __INT32_FMTd__ \"d\"\n"
        "#define __INT32_FMTi__ \"i\"\n"
        "#define __INT32_MAX__ 2147483647\n"
        "#define __INT32_TYPE__ int\n"
        "#define __INT64_C(c) c##LL\n"
        "#define __INT64_C_SUFFIX__ LL\n"
        "#define __INT64_FMTd__ \"lld\"\n"
        "#define __INT64_FMTi__ \"lli\"\n"
        "#define __INT64_MAX__ 9223372036854775807LL\n"
        "#define __INT64_TYPE__ long long int\n"
        "#define __INT8_C(c) c\n"
        "#define __INT8_C_SUFFIX__ \n"
        "#define __INT8_FMTd__ \"hhd\"\n"
        "#define __INT8_FMTi__ \"hhi\"\n"
        "#define __INT8_MAX__ 127\n"
        "#define __INT8_TYPE__ signed char\n"
        "#define __INTMAX_C(c) c##LL\n"
        "#define __INTMAX_C_SUFFIX__ LL\n"
        "#define __INTMAX_FMTd__ \"lld\"\n"
        "#define __INTMAX_FMTi__ \"lli\"\n"
        "#define __INTMAX_MAX__ 9223372036854775807LL\n"
        "#define __INTMAX_TYPE__ long long int\n"
        "#define __INTMAX_WIDTH__ 64\n"
        "#define __INTPTR_FMTd__ \"d\"\n"
        "#define __INTPTR_FMTi__ \"i\"\n"
        "#define __INTPTR_MAX__ 2147483647\n"
        "#define __INTPTR_TYPE__ int\n"
        "#define __INTPTR_WIDTH__ 32\n"
        "#define __INT_FAST16_FMTd__ \"hd\"\n"
        "#define __INT_FAST16_FMTi__ \"hi\"\n"
        "#define __INT_FAST16_MAX__ 32767\n"
        "#define __INT_FAST16_TYPE__ short\n"
        "#define __INT_FAST16_WIDTH__ 16\n"
        "#define __INT_FAST32_FMTd__ \"d\"\n"
        "#define __INT_FAST32_FMTi__ \"i\"\n"
        "#define __INT_FAST32_MAX__ 2147483647\n"
        "#define __INT_FAST32_TYPE__ int\n"
        "#define __INT_FAST32_WIDTH__ 32\n"
        "#define __INT_FAST64_FMTd__ \"lld\"\n"
        "#define __INT_FAST64_FMTi__ \"lli\"\n"
        "#define __INT_FAST64_MAX__ 9223372036854775807LL\n"
        "#define __INT_FAST64_TYPE__ long long int\n"
        "#define __INT_FAST64_WIDTH__ 64\n"
        "#define __INT_FAST8_FMTd__ \"hhd\"\n"
        "#define __INT_FAST8_FMTi__ \"hhi\"\n"
        "#define __INT_FAST8_MAX__ 127\n"
        "#define __INT_FAST8_TYPE__ signed char\n"
        "#define __INT_FAST8_WIDTH__ 8\n"
        "#define __INT_LEAST16_FMTd__ \"hd\"\n"
        "#define __INT_LEAST16_FMTi__ \"hi\"\n"
        "#define __INT_LEAST16_MAX__ 32767\n"
        "#define __INT_LEAST16_TYPE__ short\n"
        "#define __INT_LEAST16_WIDTH__ 16\n"
        "#define __INT_LEAST32_FMTd__ \"d\"\n"
        "#define __INT_LEAST32_FMTi__ \"i\"\n"
        "#define __INT_LEAST32_MAX__ 2147483647\n"
        "#define __INT_LEAST32_TYPE__ int\n"
        "#define __INT_LEAST32_WIDTH__ 32\n"
        "#define __INT_LEAST64_FMTd__ \"lld\"\n"
        "#define __INT_LEAST64_FMTi__ \"lli\"\n"
        "#define __INT_LEAST64_MAX__ 9223372036854775807LL\n"
        "#define __INT_LEAST64_TYPE__ long long int\n"
        "#define __INT_LEAST64_WIDTH__ 64\n"
        "#define __INT_LEAST8_FMTd__ \"hhd\"\n"
        "#define __INT_LEAST8_FMTi__ \"hhi\"\n"
        "#define __INT_LEAST8_MAX__ 127\n"
        "#define __INT_LEAST8_TYPE__ signed char\n"
        "#define __INT_LEAST8_WIDTH__ 8\n"
        "#define __INT_MAX__ 2147483647\n"
        "#define __INT_WIDTH__ 32\n"
        "#define __LDBL_DECIMAL_DIG__ 36\n"
        "#define __LDBL_DENORM_MIN__ 6.47517511943802511092443895822764655e-4966L\n"
        "#define __LDBL_DIG__ 33\n"
        "#define __LDBL_EPSILON__ 1.92592994438723585305597794258492732e-34L\n"
        "#define __LDBL_HAS_DENORM__ 1\n"
        "#define __LDBL_HAS_INFINITY__ 1\n"
        "#define __LDBL_HAS_QUIET_NAN__ 1\n"
        "#define __LDBL_MANT_DIG__ 113\n"
        "#define __LDBL_MAX_10_EXP__ 4932\n"
        "#define __LDBL_MAX_EXP__ 16384\n"
        "#define __LDBL_MAX__ 1.18973149535723176508575932662800702e+4932L\n"
        "#define __LDBL_MIN_10_EXP__ (-4931)\n"
        "#define __LDBL_MIN_EXP__ (-16381)\n"
        "#define __LDBL_MIN__ 3.36210314311209350626267781732175260e-4932L\n"
        "#define __LDBL_NORM_MAX__ 1.18973149535723176508575932662800702e+4932L\n"
        "#define __LITTLE_ENDIAN__ 1\n"
        "#define __LLONG_WIDTH__ 64\n"
        "#define __LONG_LONG_MAX__ 9223372036854775807LL\n"
        "#define __LONG_MAX__ 2147483647L\n"
        "#define __LONG_WIDTH__ 32\n"

        "#define __ORDER_BIG_ENDIAN__ 4321\n"
        "#define __ORDER_LITTLE_ENDIAN__ 1234\n"
        "#define __ORDER_PDP_ENDIAN__ 3412\n"
        "#define __FLT32_DECIMAL_DIG__ 9\n"
        "#define __FLT32_DENORM_MIN__ 0x1p-149f32\n"
        "#define __FLT32_DIG__ 6\n"
        "#define __FLT32_EPSILON__ 0x1p-23f32\n"
        "#define __FLT32_HAS_DENORM__ 1\n"
        "#define __FLT32_HAS_INFINITY__ 1\n"
        "#define __FLT32_HAS_QUIET_NAN__ 1\n"
        "#define __FLT32_MANT_DIG__ 24\n"
        "#define __FLT32_MAX_10_EXP__ 38\n"
        "#define __FLT32_MAX_EXP__ 128\n"
        "#define __FLT32_MAX__ 0x1.fffffep+127f32\n"
        "#define __FLT32_MIN_10_EXP__ (-37)\n"
        "#define __FLT32_MIN_EXP__ (-125)\n"
        "#define __FLT32_MIN__ 0x1p-126f32\n"
        "#define __FLT32_NORM_MAX__ 0x1.fffffep+127f32\n"
        "#define __FLT64_DECIMAL_DIG__ 17\n"
        "#define __FLT64_DENORM_MIN__ 0x0.0000000000001p-1022f64\n"
        "#define __FLT64_DIG__ 15\n"
        "#define __FLT64_EPSILON__ 0x1p-52f64\n"
        "#define __FLT64_HAS_DENORM__ 1\n"
        "#define __FLT64_HAS_INFINITY__ 1\n"
        "#define __FLT64_HAS_QUIET_NAN__ 1\n"
        "#define __FLT64_MANT_DIG__ 53\n"
        "#define __FLT64_MAX_10_EXP__ 308\n"
        "#define __FLT64_MAX_EXP__ 1024\n"
        "#define __FLT64_MAX__ 0x1.fffffffffffffp+1023f64\n"
        "#define __FLT64_MIN_10_EXP__ (-307)\n"
        "#define __FLT64_MIN_EXP__ (-1021)\n"
        "#define __FLT64_MIN__ 0x1p-1022f64\n"
        "#define __FLT64_NORM_MAX__ 0x1.fffffffffffffp+1023f64\n"
        "#define __FLT128_DECIMAL_DIG__ 36\n"
        "#define __FLT128_DENORM_MIN__ 0x1p-16494f128\n"
        "#define __FLT128_DIG__ 33\n"
        "#define __FLT128_EPSILON__ 0x1p-112f128\n"
        "#define __FLT128_HAS_DENORM__ 1\n"
        "#define __FLT128_HAS_INFINITY__ 1\n"
        "#define __FLT128_HAS_QUIET_NAN__ 1\n"
        "#define __FLT128_MANT_DIG__ 113\n"
        "#define __FLT128_MAX_10_EXP__ 4932\n"
        "#define __FLT128_MAX_EXP__ 16384\n"
        "#define __FLT128_MAX__ 0x1.ffffffffffffffffffffffffffffp+16383f128\n"
        "#define __FLT128_MIN_10_EXP__ (-4931)\n"
        "#define __FLT128_MIN_EXP__ (-16381)\n"
        "#define __FLT128_MIN__ 0x1p-16382f128\n"
        "#define __FLT128_NORM_MAX__ 0x1.ffffffffffffffffffffffffffffp+16383f128\n"
        "#define __POINTER_WIDTH__ 32\n"
        "#define __PTRDIFF_FMTd__ \"d\"\n"
        "#define __PTRDIFF_FMTi__ \"i\"\n"
        "#define __PTRDIFF_MAX__ 2147483647\n"
        "#define __PTRDIFF_TYPE__ int\n"
        "#define __PTRDIFF_WIDTH__ 32\n"
        "#define __SCHAR_MAX__ 127\n"
        "#define __SHRT_MAX__ 32767\n"
        "#define __SHRT_WIDTH__ 16\n"
        "#define __SIG_ATOMIC_MAX__ 2147483647\n"
        "#define __SIG_ATOMIC_WIDTH__ 32\n"
        "#define __SIZEOF_DOUBLE__ 8\n"
        "#define __SIZEOF_FLOAT__ 4\n"
        "#define __SIZEOF_INT__ 4\n"
        "#define __SIZEOF_LONG_DOUBLE__ 16\n"
        "#define __SIZEOF_LONG_LONG__ 8\n"
        "#define __SIZEOF_LONG__ 4\n"
        "#define __SIZEOF_POINTER__ 4\n"
        "#define __SIZEOF_PTRDIFF_T__ 4\n"
        "#define __SIZEOF_SHORT__ 2\n"
        "#define __SIZEOF_SIZE_T__ 4\n"
        "#define __SIZEOF_WCHAR_T__ 4\n"
        "#define __SIZEOF_WINT_T__ 4\n"
        "#define __SIZE_FMTX__ \"X\"\n"
        "#define __SIZE_FMTo__ \"o\"\n"
        "#define __SIZE_FMTu__ \"u\"\n"
        "#define __SIZE_FMTx__ \"x\"\n"
        "#define __SIZE_MAX__ 4294967295U\n"
        "#define __SIZE_TYPE__ unsigned int\n"
        "#define __SIZE_WIDTH__ 32\n"
        "#define __STDC_EMBED_EMPTY__ 2\n"
        "#define __STDC_EMBED_FOUND__ 1\n"
        "#define __STDC_EMBED_NOT_FOUND__ 0\n"
        "#define __STDC_HOSTED__ 1\n"
        "#define __STDC_UTF_16__ 1\n"
        "#define __STDC_UTF_32__ 1\n"
        "#define __STDC_VERSION__ 201710L\n"
        "#define __STDC__ 1\n"
        "#define __UINT16_C(c) c\n"
        "#define __UINT16_C_SUFFIX__ \n"
        "#define __UINT16_FMTX__ \"hX\"\n"
        "#define __UINT16_FMTo__ \"ho\"\n"
        "#define __UINT16_FMTu__ \"hu\"\n"
        "#define __UINT16_FMTx__ \"hx\"\n"
        "#define __UINT16_MAX__ 65535\n"
        "#define __UINT16_TYPE__ unsigned short\n"
        "#define __UINT32_C(c) c##U\n"
        "#define __UINT32_C_SUFFIX__ U\n"
        "#define __UINT32_FMTX__ \"X\"\n"
        "#define __UINT32_FMTo__ \"o\"\n"
        "#define __UINT32_FMTu__ \"u\"\n"
        "#define __UINT32_FMTx__ \"x\"\n"
        "#define __UINT32_MAX__ 4294967295U\n"
        "#define __UINT32_TYPE__ unsigned int\n"
        "#define __UINT64_C(c) c##ULL\n"
        "#define __UINT64_C_SUFFIX__ ULL\n"
        "#define __UINT64_FMTX__ \"llX\"\n"
        "#define __UINT64_FMTo__ \"llo\"\n"
        "#define __UINT64_FMTu__ \"llu\"\n"
        "#define __UINT64_FMTx__ \"llx\"\n"
        "#define __UINT64_MAX__ 18446744073709551615ULL\n"
        "#define __UINT64_TYPE__ long long unsigned int\n"
        "#define __UINT8_C(c) c\n"
        "#define __UINT8_C_SUFFIX__ \n"
        "#define __UINT8_FMTX__ \"hhX\"\n"
        "#define __UINT8_FMTo__ \"hho\"\n"
        "#define __UINT8_FMTu__ \"hhu\"\n"
        "#define __UINT8_FMTx__ \"hhx\"\n"
        "#define __UINT8_MAX__ 255\n"
        "#define __UINT8_TYPE__ unsigned char\n"
        "#define __UINTMAX_C(c) c##ULL\n"
        "#define __UINTMAX_C_SUFFIX__ ULL\n"
        "#define __UINTMAX_FMTX__ \"llX\"\n"
        "#define __UINTMAX_FMTo__ \"llo\"\n"
        "#define __UINTMAX_FMTu__ \"llu\"\n"
        "#define __UINTMAX_FMTx__ \"llx\"\n"
        "#define __UINTMAX_MAX__ 18446744073709551615ULL\n"
        "#define __UINTMAX_TYPE__ long long unsigned int\n"
        "#define __UINTMAX_WIDTH__ 64\n"
        "#define __UINTPTR_FMTX__ \"X\"\n"
        "#define __UINTPTR_FMTo__ \"o\"\n"
        "#define __UINTPTR_FMTu__ \"u\"\n"
        "#define __UINTPTR_FMTx__ \"x\"\n"
        "#define __UINTPTR_MAX__ 4294967295U\n"
        "#define __UINTPTR_TYPE__ unsigned int\n"
        "#define __UINTPTR_WIDTH__ 32\n"
        "#define __UINT_FAST16_FMTX__ \"hX\"\n"
        "#define __UINT_FAST16_FMTo__ \"ho\"\n"
        "#define __UINT_FAST16_FMTu__ \"hu\"\n"
        "#define __UINT_FAST16_FMTx__ \"hx\"\n"
        "#define __UINT_FAST16_MAX__ 65535\n"
        "#define __UINT_FAST16_TYPE__ unsigned short\n"
        "#define __UINT_FAST32_FMTX__ \"X\"\n"
        "#define __UINT_FAST32_FMTo__ \"o\"\n"
        "#define __UINT_FAST32_FMTu__ \"u\"\n"
        "#define __UINT_FAST32_FMTx__ \"x\"\n"
        "#define __UINT_FAST32_MAX__ 4294967295U\n"
        "#define __UINT_FAST32_TYPE__ unsigned int\n"
        "#define __UINT_FAST64_FMTX__ \"llX\"\n"
        "#define __UINT_FAST64_FMTo__ \"llo\"\n"
        "#define __UINT_FAST64_FMTu__ \"llu\"\n"
        "#define __UINT_FAST64_FMTx__ \"llx\"\n"
        "#define __UINT_FAST64_MAX__ 18446744073709551615ULL\n"
        "#define __UINT_FAST64_TYPE__ long long unsigned int\n"
        "#define __UINT_FAST8_FMTX__ \"hhX\"\n"
        "#define __UINT_FAST8_FMTo__ \"hho\"\n"
        "#define __UINT_FAST8_FMTu__ \"hhu\"\n"
        "#define __UINT_FAST8_FMTx__ \"hhx\"\n"
        "#define __UINT_FAST8_MAX__ 255\n"
        "#define __UINT_FAST8_TYPE__ unsigned char\n"
        "#define __UINT_LEAST16_FMTX__ \"hX\"\n"
        "#define __UINT_LEAST16_FMTo__ \"ho\"\n"
        "#define __UINT_LEAST16_FMTu__ \"hu\"\n"
        "#define __UINT_LEAST16_FMTx__ \"hx\"\n"
        "#define __UINT_LEAST16_MAX__ 65535\n"
        "#define __UINT_LEAST16_TYPE__ unsigned short\n"
        "#define __UINT_LEAST32_FMTX__ \"X\"\n"
        "#define __UINT_LEAST32_FMTo__ \"o\"\n"
        "#define __UINT_LEAST32_FMTu__ \"u\"\n"
        "#define __UINT_LEAST32_FMTx__ \"x\"\n"
        "#define __UINT_LEAST32_MAX__ 4294967295U\n"
        "#define __UINT_LEAST32_TYPE__ unsigned int\n"
        "#define __UINT_LEAST64_FMTX__ \"llX\"\n"
        "#define __UINT_LEAST64_FMTo__ \"llo\"\n"
        "#define __UINT_LEAST64_FMTu__ \"llu\"\n"
        "#define __UINT_LEAST64_FMTx__ \"llx\"\n"
        "#define __UINT_LEAST64_MAX__ 18446744073709551615ULL\n"
        "#define __UINT_LEAST64_TYPE__ long long unsigned int\n"
        "#define __UINT_LEAST8_FMTX__ \"hhX\"\n"
        "#define __UINT_LEAST8_FMTo__ \"hho\"\n"
        "#define __UINT_LEAST8_FMTu__ \"hhu\"\n"
        "#define __UINT_LEAST8_FMTx__ \"hhx\"\n"
        "#define __UINT_LEAST8_MAX__ 255\n"
        "#define __UINT_LEAST8_TYPE__ unsigned char\n"
        "#define __USER_LABEL_PREFIX__ \n"
        "#define __WCHAR_MAX__ 2147483647\n"
        "#define __WCHAR_TYPE__ int\n"
        "#define __WCHAR_WIDTH__ 32\n"
        "#define __WINT_MAX__ 4294967295U\n"
        "#define __WINT_TYPE__ unsigned int\n"
        "#define __WINT_UNSIGNED__ 1\n"
        "#define __WINT_WIDTH__ 32\n"
        "#define __riscv 1\n"
        "#define __riscv_arch_test 1\n"
        "#define __riscv_c 2000000\n"
        "#define __riscv_cmodel_medlow 1\n"
        "#define __riscv_compressed 1\n"
        "#define __riscv_div 1\n"
        "#define __riscv_float_abi_soft 1\n"
        "#define __riscv_i 2001000\n"
        "#define __riscv_m 2000000\n"
        "#define __riscv_misaligned_avoid 1\n"
        "#define __riscv_mul 1\n"
        "#define __riscv_muldiv 1\n"
        "#define __riscv_v_intrinsic 1000000\n"
        "#define __riscv_xlen 32\n"
        "#define __riscv_zca 1000000\n"
        "#define __riscv_zmmul 1000000\n"
        "#define __cxx__ 1\n"
        "#define __STDC_NO_ATOMICS__ 1\n"
        "#define __STDC_NO_COMPLEX__ 1\n"
        "#define __alignof__ _Alignof\n"
        "#define __const__ const\n"
        "#define __has_include __has_include\n"
        "#define __inline__ inline\n"
        "#define __signed__ signed\n"
        "#define __typeof__ typeof\n"
        "#define __volatile__ volatile\n",
};
