static const char *op_str[][IR_CNT] = {
    {
        [IR_ADD] = "add",
        [IR_SUB] = "sub",
        [IR_MUL] = "mul",
        [IR_DIV] = "sdiv",
        [IR_REM] = "srem",
        [IR_AND] = "and",
        [IR_OR] = "or",
        [IR_XOR] = "xor",
        [IR_SHL] = "shl",
        [IR_SHR] = "ashr",
        [IR_CMP_EQ] = "icmp eq",
        [IR_CMP_NE] = "icmp ne",
        [IR_CMP_LE] = "icmp sle",
        [IR_CMP_LT] = "icmp slt",
        [IR_EXT] = "sext",
        [IR_TRUNC] = "trunc",
        [IR_FPTOINT] = "fptosi",
        [IR_INTTOFP] = "sitofp",
        [IR_PTRTOINT] = "ptrtoint",
        [IR_INTTOPTR] = "inttoptr",
    },
    {
        [IR_ADD] = "add",
        [IR_SUB] = "sub",
        [IR_MUL] = "mul",
        [IR_DIV] = "udiv",
        [IR_REM] = "urem",
        [IR_AND] = "and",
        [IR_OR] = "or",
        [IR_XOR] = "xor",
        [IR_SHL] = "shl",
        [IR_SHR] = "lshr",
        [IR_CMP_EQ] = "icmp eq",
        [IR_CMP_NE] = "icmp ne",
        [IR_CMP_LE] = "icmp ule",
        [IR_CMP_LT] = "icmp ult",
        [IR_EXT] = "sext",
        [IR_TRUNC] = "trunc",
        [IR_FPTOINT] = "fptoui",
        [IR_INTTOFP] = "uitofp",
        [IR_PTRTOINT] = "ptrtoint",
        [IR_INTTOPTR] = "inttoptr",
    },
    {
        [IR_ADD] = "fadd",
        [IR_SUB] = "fsub",
        [IR_MUL] = "fmul",
        [IR_DIV] = "fdiv",
        [IR_REM] = "frem",
        [IR_AND] = "and",
        [IR_OR] = "or",
        [IR_XOR] = "xor",
        [IR_SHL] = "shl",
        [IR_SHR] = "lshr",
        [IR_CMP_EQ] = "fcmp oeq",
        [IR_CMP_NE] = "fcmp one",
        [IR_CMP_LE] = "fcmp ole",
        [IR_CMP_LT] = "fcmp olt",
        [IR_EXT] = "fpext",
        [IR_TRUNC] = "fptrunc",
        [IR_FPTOINT] = "fptosi",
        [IR_INTTOFP] = "sitofp",
        [IR_PTRTOINT] = "ptrtoint",
        [IR_INTTOPTR] = "inttoptr",
    },
};